version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:230339925016:task/ecs-cluster/aefc2bdc82254be3afcd61a6a3295bf6
        LoadBalancerInfo:
          ContainerName: "sample-website"
          ContainerPort: 80
