version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:230339925016:task-definition/ecs-lab:6
        LoadBalancerInfo:
          ContainerName: "sample-website"
          ContainerPort: 80
